In [1]:
import numpy as np

### `Q-1` Create a null vector of size 10 but the fifth value which is 1.

In [72]:
null = np.empty(10)
null[4] = 1

In [6]:
null

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### `Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [23]:
a,b = map(int, input("Please enter the number: ").split())
array = np.random.random((a,b))
print(array)
print(array.mean())

Please enter the number: 2 4
[[0.35540995 0.09738523 0.03362225 0.65964848]
 [0.35221234 0.80028359 0.48268654 0.86503678]]
0.4557856438672382


### `Q-3` Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

In [70]:
def array_creation(a,b):
    array1 = np.ones((a,b))
    array1[1:-1,1:-1] = 0
    print(array1)

array_creation(4,4)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


### `Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [77]:
arr = np.linspace(0,1,12)[1:-1]
arr

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

### `Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [85]:
# Cannot create the matrix as there is not 3,4 matrix

### `Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [92]:
arr = np.arange(0,5)
np.vstack((arr,arr,arr,arr,arr))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### `Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3]) 
```


In [109]:
a = np.random.randint(1,100 ,(10,2))
p = np.array([2,3])
a

array([[36, 38],
       [14, 96],
       [96, 90],
       [98, 25],
       [80, 89],
       [39, 56],
       [ 5, 70],
       [54, 28],
       [23, 79],
       [93, 34]])

In [110]:
(np.sum(((a-p)**2),axis=1)**0.5).astype(int)

array([ 48,  93, 128,  98, 116,  64,  67,  57,  78,  96])

### `Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [122]:
arr = np.random.rand(6,7,8)
arr

array([[[0.33787638, 0.34617386, 0.00396924, 0.807662  , 0.64795512,
         0.28470992, 0.60955775, 0.77733583],
        [0.73568338, 0.93525096, 0.57207827, 0.98867058, 0.00800218,
         0.21203062, 0.52944666, 0.58386853],
        [0.01009546, 0.97124108, 0.92519065, 0.31252797, 0.85694748,
         0.81704232, 0.88084361, 0.18485885],
        [0.53633227, 0.73676387, 0.3267117 , 0.63775891, 0.33584687,
         0.26897291, 0.47943096, 0.43088175],
        [0.42305375, 0.97299614, 0.69810826, 0.35819604, 0.5097238 ,
         0.2118261 , 0.29618848, 0.08376333],
        [0.91671313, 0.31201776, 0.6770577 , 0.09523822, 0.14007895,
         0.5492539 , 0.86383586, 0.47750689],
        [0.1774179 , 0.14982222, 0.04874099, 0.88424795, 0.15029369,
         0.34678504, 0.26127502, 0.79425544]],

       [[0.02645573, 0.09457597, 0.0670498 , 0.87177796, 0.98919716,
         0.89569961, 0.80605229, 0.86125516],
        [0.61046897, 0.15490568, 0.26540507, 0.73883404, 0.59979203,
         

In [123]:
np.ravel(arr)[99]

0.642078097039922

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [134]:
numbers = "1 2 3 4 -8 -10"

num = np.array(list(map(float,numbers.split())))

In [135]:
num[::-1]

array([-10.,  -8.,   4.,   3.,   2.,   1.])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [136]:
a = np.array([2,35,2,5,7,8])
np.size(a)

6

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01, 
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [157]:
def softmax(arr):
    if type(arr) != np.ndarray:
        raise TypeError("The given array is not numpy array")
    elif np.ndim(arr) > 1:
        raise TypeError("Enter the 1D array")
    arr = (np.exp(arr))/(np.sum(np.exp(arr)))
    print(arr)
    
softmax(np.array([86.03331084, 37.7285648, 48.64908087, 87.16563062, 38.40852563, 37.20006318]))

[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]] 
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [178]:
def vertical_stack(x,y):
    if type(x) != np.ndarray and type(y) != np.ndarray:
        raise TypeError("parameter passed is not numpy array")
    arr = np.vstack((x,y))
    print(arr)
    
a = np.identity(5)
b = np.arange(0,10).reshape(2,5)
print(a)
print(b)
vertical_stack(a,b)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [199]:
def date_array(start= str, end=str):
    if type(start) and type(end) != str:
        raise TypeError("The given parameter should be string only")
    return np.arange(start, end ,dtype= 'datetime64[D]')
date_array('2022-10-22','2023-01-05')

array(['2022-10-22', '2022-10-23', '2022-10-24', '2022-10-25',
       '2022-10-26', '2022-10-27', '2022-10-28', '2022-10-29',
       '2022-10-30', '2022-10-31', '2022-11-01', '2022-11-02',
       '2022-11-03', '2022-11-04', '2022-11-05', '2022-11-06',
       '2022-11-07', '2022-11-08', '2022-11-09', '2022-11-10',
       '2022-11-11', '2022-11-12', '2022-11-13', '2022-11-14',
       '2022-11-15', '2022-11-16', '2022-11-17', '2022-11-18',
       '2022-11-19', '2022-11-20', '2022-11-21', '2022-11-22',
       '2022-11-23', '2022-11-24', '2022-11-25', '2022-11-26',
       '2022-11-27', '2022-11-28', '2022-11-29', '2022-11-30',
       '2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04',
       '2022-12-05', '2022-12-06', '2022-12-07', '2022-12-08',
       '2022-12-09', '2022-12-10', '2022-12-11', '2022-12-12',
       '2022-12-13', '2022-12-14', '2022-12-15', '2022-12-16',
       '2022-12-17', '2022-12-18', '2022-12-19', '2022-12-20',
       '2022-12-21', '2022-12-22', '2022-12-23', '2022-

### `Q-14:` Subtract the mean of each row from a matrix.

In [239]:
a = np.arange(8).reshape(4,2)
print(a)
a-np.mean(a,axis=1,keepdims=True)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


array([[-0.5,  0.5],
       [-0.5,  0.5],
       [-0.5,  0.5],
       [-0.5,  0.5]])

### `Q-15:` Swap column-1 of array with column-2 in the array.

In [214]:
arr = np.random.rand(3,4)
arr

array([[0.69772949, 0.36129734, 0.25371858, 0.45947048],
       [0.30180989, 0.80476802, 0.28296169, 0.54868618],
       [0.46597933, 0.81843819, 0.71745917, 0.50644264]])

In [240]:
arr[:,[0,2,1,3]]

array([[0.69772949, 0.25371858, 0.36129734, 0.45947048],
       [0.30180989, 0.28296169, 0.80476802, 0.54868618],
       [0.46597933, 0.71745917, 0.81843819, 0.50644264]])

### `Q-16:` Replace odd elements in arrays with -1.

In [247]:
a = np.arange(13)
a[a%2 == 1] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12])

### `Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
``` 

In [278]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
a[b>a] = b[a<b]
a

array([6, 3, 1, 7, 8])

### `Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [287]:
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
print(arr1)
alternate_arr = arr1[:,::2]
(arr1-np.min(arr1))/(np.max(arr1)-np.min(arr1))

[[8662 5763 8747 2167 4490]
 [1334 6006 9804 6255 8597]
 [7859 8197 2028 4851 1652]
 [8518 3425 3200 5650 7637]
 [6029 9472 4287 1460 1139]
 [4343 4409 6324 7832 6997]
 [1158 1835 4104 6014 8767]
 [ 707 2783 9692 7047 2391]]


array([[0.87446411, 0.55578762, 0.88380785, 0.16049247, 0.41585138],
       [0.06892382, 0.58249973, 1.        , 0.60987139, 0.8673189 ],
       [0.78619325, 0.82334836, 0.14521271, 0.45553479, 0.1038804 ],
       [0.85863471, 0.29877982, 0.27404639, 0.54336594, 0.7617896 ],
       [0.58502803, 0.96350445, 0.39353633, 0.08277454, 0.04748818],
       [0.39969221, 0.40694735, 0.6174563 , 0.78322524, 0.69143674],
       [0.04957678, 0.12399692, 0.37341981, 0.58337914, 0.88600638],
       [0.        , 0.2282071 , 0.98768825, 0.69693305, 0.18511597]])

### `Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [293]:
def nth_largest(arr,n):
    if type(arr) != np.ndarray:
        raise TypeError('The given array is not numpy array')
    elif n > len(arr):
        raise TypeError('The given n value is higher then length of array')
    arr=np.sort(arr)
    return arr[-n]
nth_largest(np.array([12,34,40,7,1,0]),3)

12

### `Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [308]:
a = np.array([1,2,3])
np.hstack((np.repeat(a,3), np.tile(a,3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])